### ISSUE TITLE
Store Image generates an exception if imageName is not specified

### ISSUE THREAD

**Issue by rmthurman** [Azure-Samples/azure-search-power-skills#49]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>  Deploy as is and do not specify an imageName

### Any log messages given by the failure
>  Web Api skill response contains errors: 'Web Api response contains both data and errors. Will not process Data.;image-store - Error processing the request record : System.Collections.Generic.KeyNotFoundException: The given key 'imageName' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at AzureCognitiveSearch.PowerSkills.Vision.ImageStore.ImageStore.<>c__DisplayClass3_0.<<RunStoreImage>b__0>d.MoveNext() in C:\home\site\repository\Vision\ImageStore\ImageStore.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at AzureCognitiveSearch.PowerSkills.Common.WebApiSkillHelpers.ProcessRequestRecordsAsync(String functionName, IEnumerable`1 requestRecords, Func`3 processRecord) in C:\home\site\repository\Common\WebAPISkillHelper.cs:line 67'.

### Expected/desired behavior
> should generate a GUID and succeed

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by gmndrg** [comment]
Closing old issue that was either addressed at the time or native skills support the capability vs. a power skill.
